version: "3.9"

services:
  db:
    image: "postgres"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "80:3000"
    entrypoint: ["/bin/sh", "./src/scripts/entrypoint.sh"]
    depends_on:
      - db
      
volumes:
  pgdata: